"""Export the dictionary to a Rime schema (fcitx5-rime / ibus-rime).

Rime is the other big Linux IME framework: installing this schema gives
system-wide Nepali transliteration inside fcitx5-rime or ibus-rime,
alongside the native IBus engine in ibus/.

Usage:
    python3 tools/export_rime.py [--out DIR]   # default: rime/

Writes DIR/nepali_translit.dict.yaml + DIR/nepali_translit.schema.yaml.
Hand entries come first (priority), then imports. All keys are plain
lowercase a-z, matching the default speller alphabet.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from core import __version__ as ENGINE_VERSION
from core.dictionary import WORD_CORRECTIONS
from core.words_auto import AUTO_CORRECTIONS

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")

SCHEMA_TEMPLATE = """\
# Rime schema: Nepali Transliterate (GENERATED by tools/export_rime.py).
# Romanized Nepali transliteration from the nepali-transl dictionary.
schema:
  schema_id: nepali_translit
  name: Nepali Transliterate
  version: "{version}"
  description: Romanized Nepali transliteration (offline dictionary)
engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - table_translator
speller:
  alphabet: abcdefghijklmnopqrstuvwxyz
  delimiter: " '"
translator:
  dictionary: nepali_translit
  spelling_hints: 5
"""

DICT_HEADER = """\
# Rime dictionary: Nepali Transliterate (GENERATED by tools/export_rime.py).
# Format: <Devanagari word><TAB><roman code>. Hand entries first.
---
name: nepali_translit
version: "{version}"
sort: original
columns:
  - text
  - code
encoder:
  exclude_patterns:
    - '^.$'
    - '^..$'
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaAbAcBaBbBcCaCbCc"
    - length_in_range: [4, 10]
      formula: "AaBaCaDa"
...
"""


def build_rows():
    """[(form, code)] hand-first, de-duplicated (hand wins collisions)."""
    rows, seen = [], set()
    for table in (WORD_CORRECTIONS, AUTO_CORRECTIONS):
        for key in sorted(table):
            form = table[key]
            if key in seen:
                continue
            seen.add(key)
            rows.append((form, key))
    return rows


def export(out_dir):
    os.makedirs(out_dir, exist_ok=True)
    rows = build_rows()
    with open(os.path.join(out_dir, "nepali_translit.schema.yaml"),
              "w", encoding="utf-8") as f:
        f.write(SCHEMA_TEMPLATE.format(version=ENGINE_VERSION))
    with open(os.path.join(out_dir, "nepali_translit.dict.yaml"),
              "w", encoding="utf-8") as f:
        f.write(DICT_HEADER.format(version=ENGINE_VERSION))
        for form, code in rows:
            f.write(f"{form}\t{code}\n")
    print(f"exported {len(rows)} entries to {out_dir}/")
    return rows


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "rime"))
    args = ap.parse_args(argv)
    export(args.out)


if __name__ == "__main__":
    main()
