"""Import romanized<->Devanagari pairs into core/words_auto.py.

Source: Saugatkafley/Nepali-Roman-Transliteration (HuggingFace, MIT license)
  - nep_valid.json + nep_test.json (~6.9k pairs, native word + romanization)
Only pairs our phonetic engine does NOT already produce are imported, so the
generated file is exactly the "engine blind spots" set.

Usage:
    python3 tools/import_pairs.py /tmp/nep_valid.json /tmp/nep_test.json

Writes: core/words_auto.py  (AUTO_CORRECTIONS dict + provenance header)
"""
import json
import os
import sys
from collections import OrderedDict

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from core.nepali_transl import NepaliTransliterator
from core.dictionary import WORD_CORRECTIONS

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")


def load_rows(paths):
    rows = []
    for p in paths:
        with open(p, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    rows.append(json.loads(line))
    return rows


SRC_RANK = {"AK-Freq": 0, "AK-Uni": 1, "Wikidata": 2, "IndicCorp": 3}


def _score(v):
    return v if isinstance(v, (int, float)) else -999.0


def _rank(r):
    return (SRC_RANK.get(r.get("source"), 9), -_score(r.get("score")))


def build_auto(rows):
    """Build {roman: native} corrections from pair rows.

    Same rules everywhere (import + honest eval share this): curated
    sources first, phonetic-owned keys stay phonetic, hand entries win,
    first collision wins. Returns (auto_dict, stats).
    """
    rows = sorted(rows, key=_rank)
    tr = NepaliTransliterator()
    auto = OrderedDict()
    stats = {"total": len(rows), "phonetic_ok": 0, "hand_covered": 0,
             "imported": 0, "collisions": 0, "skipped_short": 0,
             "phonetic_owned": 0}

    # Pass 1: keys the pure phonetic engine already resolves to a real
    # dataset native form are OWNED by phonetics — variants must not
    # override them (e.g. anu->अनु beats dataset variant anu->अणु).
    dataset_natives = {r["native word"] for r in rows}
    phonetic_owned = set()
    for r in rows:
        key = r["english word"].strip().lower()
        if tr._transliterate_word(key, use_dict=False) in dataset_natives:
            phonetic_owned.add(key)

    for r in rows:
        native = r["native word"]
        key = r["english word"].strip().lower()
        if len(key) < 2 or len(native) < 2:
            stats["skipped_short"] += 1
            continue
        if key in phonetic_owned:
            # Pure phonetic engine already correct? -> no dictionary needed.
            if tr._transliterate_word(key, use_dict=False) == native:
                stats["phonetic_ok"] += 1
            else:
                stats["phonetic_owned"] += 1
            continue
        # Hand-curated entry already covers it? -> keep hand version.
        if WORD_CORRECTIONS.get(key) == native:
            stats["hand_covered"] += 1
            continue
        if key in WORD_CORRECTIONS:
            # Hand entry disagrees: trust the human, skip noisy pair.
            stats["hand_covered"] += 1
            continue
        if key in auto:
            stats["collisions"] += 1
            continue  # rows pre-sorted: first wins (curated first)
        auto[key] = (native, _score(r.get("score")))
        stats["imported"] += 1
    return auto, stats


def main(argv):
    paths = argv[1:] or ["/tmp/nep_valid.json", "/tmp/nep_test.json"]
    rows = load_rows(paths)
    print(f"loaded {len(rows)} pairs")

    scores = [r["score"] for r in rows
                if isinstance(r.get("score"), (int, float))]
    if scores:
        print(f"score range: {min(scores):.3f} .. {max(scores):.3f}")

    auto, stats = build_auto(rows)
    print("stats:", stats)

    out_path = os.path.join(ROOT, "core", "words_auto.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write('"""Auto-imported romanized->Devanagari corrections.\n\n')
        f.write('Source: Saugatkafley/Nepali-Roman-Transliteration (HuggingFace)\n')
        f.write('License of source data: MIT. This file: same as project (GPL-2.0+).\n')
        f.write('Generated by: python3 tools/import_pairs.py\n')
        f.write(f"Stats: {stats}\n")
        f.write('DO NOT EDIT BY HAND - regenerate instead. Hand overrides live in\n')
        f.write('core/dictionary.py WORD_CORRECTIONS (checked before this table).\n')
        f.write('"""\n\nAUTO_CORRECTIONS = {\n')
        for key in sorted(auto):
            native = auto[key][0]
            f.write(f"    {key!r}: {native!r},\n")
        f.write("}\n")
    print(f"wrote {out_path} ({len(auto)} entries)")


if __name__ == "__main__":
    main(sys.argv)
