"""Build core/words_suggest.py from the Roman corpus frequency list.

A roman token becomes a suggestion key only if it is plausibly Nepali:
its full transliteration (hand + auto + phonetic) must land in the
Brihat Sabdakosh headword set, or the token itself must be a dictionary
key. This keeps English leaks (india, time, was) OUT while admitting
real typed forms (tapai, vayo, xaina).

Inputs (in /tmp, see plan Phase 13):
  roman_freq.json  token -> count (Nepali-Flow-Roman 307k rows, CC-BY-4.0)
  sabda_words.json Devanagari headword list (Brihat Sabdakosh, MIT)

Usage:
    python3 tools/import_roman.py
Writes: core/words_suggest.py (ROMAN_SUGGESTIONS + provenance header)
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from core.nepali_transl import NepaliTransliterator
from core.dictionary import WORD_CORRECTIONS
from core.words_auto import AUTO_CORRECTIONS

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
MIN_FREQ = 8
HIGH_FREQ = 300  # very frequent social-text tokens: keep unless English


def _english_vocab():
    try:
        from wordfreq import top_n_list
        return set(top_n_list("en", 50000))
    except Exception:
        return set()


def main(argv=None):
    freq = json.load(open("/tmp/roman_freq.json", encoding="utf-8"))
    with open("/tmp/sabda_words.json", encoding="utf-8") as f:
        sabda = set(json.load(f))
    en_vocab = _english_vocab()
    tr = NepaliTransliterator()
    kept, english_like, rare = [], [], 0
    for word, count in sorted(freq.items(), key=lambda kv: -kv[1]):
        if count < MIN_FREQ:
            rare += 1
            continue
        if word in WORD_CORRECTIONS or word in AUTO_CORRECTIONS:
            kept.append(word)  # dictionary-backed: meaning known
        elif tr.transliterate(word) in sabda:
            kept.append(word)  # lands on a real headword
        elif count >= HIGH_FREQ and word not in en_vocab:
            kept.append(word)  # frequent in Nepali text, not English
        else:
            english_like.append(word)
    print(f"kept={len(kept)} dropped-noise={len(english_like)} rare={rare}")
    print("sample kept:", kept[:12])
    print("sample dropped:", english_like[:12])

    out_path = os.path.join(ROOT, "core", "words_suggest.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write('"""Roman suggestion keys mined from real typed Nepali.\n\n')
        f.write('Source: Boredoom17/Nepali-Flow-Roman (HuggingFace, CC-BY-4.0).\n')
        f.write('Kept only tokens that transliterate onto Brihat Sabdakosh\n')
        f.write('(MIT) headwords or are dictionary keys. Generated by\n')
        f.write('tools/import_roman.py — regenerate, do not hand-edit.\n')
        f.write('"""\n\nROMAN_SUGGESTIONS = [\n')
        for word in sorted(kept):
            f.write(f"    {word!r},\n")
        f.write("]\n")
    print(f"wrote {out_path} ({len(kept)} keys)")


if __name__ == "__main__":
    main(sys.argv)
